# Generated by Django 5.1.3 on 2024-11-24 00:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizingImages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('default_image', models.ImageField(upload_to='default_images')),
                ('optimized_image', models.ImageField(blank=True, null=True, upload_to='optimized_image')),
                ('status', models.CharField(choices=[('awaiting', 'Aguardando Processamento'), ('processing', 'Em Processamento'), ('processed', 'Processado')], default='awaiting', max_length=20)),
                ('mode', models.CharField(choices=[('Sync', 'Síncrono'), ('Async', 'Assíncrono')], default='Sync', max_length=10)),
                ('format', models.CharField(choices=[('jpeg', 'JPEG'), ('png', 'PNG'), ('webp', 'WEBP'), ('jpg', 'JPG')], default='jpeg', max_length=10)),
                ('compression', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('complete_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('status', models.IntegerField()),
                ('request', models.JSONField()),
                ('response', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
