# Generated by Django 5.1.3 on 2024-11-23 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditcards',
            old_name='last_number_credit_card',
            new_name='last_numbers_credit_card',
        ),
    ]
